export var global = {
    userapiurl: 'http://proleagapi.qseksolutions.com/api/v1/users/',
    cricketurl: 'http://proleagapi.qseksolutions.com/api/v1/cricket/',
    // HeaderData: 'S9/8tnNVoSZ3zAUxUTBrrs8d6B0Iynxt7Y+zM+d7fIM=',
    teamImgUrl: 'http://proleag.qseksolutions.com/fantasyCricket/img/teams/',
    proTitle: 'proleag',
    USER_ID: '1',
    PAGE_NO: '1',
    app_version: '1.0',
    device_token: '1.0',
    login: 'login',
    register: 'register',
    forgot_password: 'forgot_password',
    match_list: 'league',
};